export const ROUTES = {
  home: "/",
  login: "/login",
  dashboard: "/dashboard",
  schools: "/schools",
  buses: "/buses",
  students: "/students",
  /** Supervisors + drivers (`?tab=`). */
  users: "/users",
  drivers: "/drivers",
  supervisors: "/supervisors",
  areas: "/areas",
  parentRequests: "/parent-requests",
  reviews: "/reviews",
  notifications: "/notifications",
  reports: "/reports",
  admins: "/admins",
  settings: "/settings",
  profile: "/profile",
  deleteAccount: "/delete-account",
} as const;
